#cloud-config

write_files:
- path: /tmp/amazon-cloudwatch-agent.json
  permissions: '0644'
  content: |
    {
      "logs": {
        "log_stream_name": "{instance_id}",
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/syslog",
                "log_group_name": "LOG_GROUP_NAME",
                "timestamp_format": "%Y-%m-%dT%H:%M:%S"
              }
            ]
          }
        }
      }
    }

runcmd:
- curl -o /tmp/amazon-cloudwatch-agent.deb https://amazoncloudwatch-agent-REGION_NAME.s3.REGION_NAME.amazonaws.com/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb
- dpkg -i /tmp/amazon-cloudwatch-agent.deb
- rm /tmp/amazon-cloudwatch-agent.deb
- mv /tmp/amazon-cloudwatch-agent.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
- systemctl enable amazon-cloudwatch-agent
- systemctl start amazon-cloudwatch-agent
