console.log('Loading function');

const aws = require('aws-sdk');
const https = require('https');

const s3 = new aws.S3({ apiVersion: '2006-03-01' });

const fetchURL = function(url) {
    return new Promise(function(resolve, reject) {
        let dataString = '';
        const req = https.get(url,
            function(res) {
                res.on('data', function(chunk) {
                    dataString += chunk;
                });
                res.on('end', function() {
                    resolve({
                        status: res.statusCode,
                        content: dataString
                    });
                });
            }
        );

        req.on('error', function(e) {
            reject(e);
        });
    });
};

exports.handler = async (event, context) => {
    console.log(event)
    const objectContext = event.getObjectContext;
    
    const path = new URL(event.userRequest.url).pathname;
    const response = await fetchURL(objectContext.inputS3Url);
    console.log(response.status)
    console.log(response.content)
    
    let transformedResponse = ''
    if (response.status < 300) {
        transformedResponse = '<transformed by object lambda>'+response.content+'</transformed by object lambda>'
    } else {
        transformedResponse = '<generated by object lambda>S3 backend returned '+response.status+' for '+path+'</generated by object lambda>'
    }
    
    await s3.writeGetObjectResponse({
        Body: transformedResponse,
        RequestRoute: objectContext.outputRoute,
        RequestToken: objectContext.outputToken
    }).promise();
    console.log('Wrote response to client');
    
    return { 'status_code': 200 };
};
